#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

.config/polybar/shades/launch-focus.sh &
killall picom &


bspc monitor eDP -d I II III IV V VI VII VIII IX X
my_laptop_external_monitor=$(xrandr --query | grep 'HDMI-A-0')
if [[ $my_laptop_external_monitor == *2000x1200+2000+0* ]]; then
    bspc monitor eDP -d I II III IV V 
    bspc monitor HDMI-A-0 -d VI VII VIII IX X
fi

bspc config border_width         1
bspc config window_gap           1

# Colors
. "${HOME}/.cache/wal/colors.sh"
# bspc config normal_border_color "$color15"
# bspc config active_border_color "$color15"
# bspc config focused_border_color "$color15"
# bspc config presel_feedback_color "$color15"

bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"


bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a scrcpy state=floating rectangle=600x360+660+700
bspc rule -a Pilorama state=floating 
bspc config external_rules_command "$HOME/.config/bspwm/spotify.sh"
