#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

.config/polybar/shades/launch.sh &

bspc monitor eDP -n 0 -d I II III IV V
my_laptop_external_monitor=$(xrandr --query | grep 'DisplayPort-0')                 
echo $my_laptop_external_monitor                                                    
if [[ $my_laptop_external_monitor != *disconnected* ]]; then                         
    bspc monitor DisplayPort-0 -n 1 -d VI VII VIII IX X
fi     
bspc config border_width         2
bspc config window_gap          12

# Colors
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color115"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color3"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a kitty desktop='^1'
bspc rule -a google-chrome desktop='^2'
