#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

.config/polybar/shades/launch-focus.sh &
killall picom &

bspc monitor eDP -d I II III IV V VI VII VIII IX X
bspc config border_width         1
bspc config window_gap           0

# Colors
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color15"
bspc config active_border_color "$color15"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color15"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a scrcpy state=floating rectangle=600x360+660+700
bspc config external_rules_command "$HOME/.config/bspwm/spotify.sh"
